<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>group2_final_interfaces</name>
  <version>0.0.1</version>
  <description>Our (Group 2) custom service interfaces for the final project.</description>

  <maintainer email="maxyk@umd.edu">maxyk</maintainer>
  <maintainer email="gfacchet@terpmail.umd.edu">namfacchetti</maintainer>  
  <license>Apache-2.0</license>

  <!--  generate the .srv interfaces -->
  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <!-- Needed at runtime so other packages can import the generated types -->
  <exec_depend>rosidl_default_runtime</exec_depend>

  <!-- ReportSurvivor.srv uses geometry_msgs/PointStamped -->
  <depend>geometry_msgs</depend>

  <!-- Marks this package as one that produces ROS 2 interfaces -->
  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>